package vodmordia.modtabs.config;

import vodmordia.modtabs.ModTabs;

public class Config
{
	// Old NeoForge config system completely removed - now using MidnightConfig only

	public static class Baked
	{
		// Global icon-offset & paging from the General tab of the in-game settings modal.
		public static int iconOffsetTop;
		public static int iconOffsetRight;
		public static int iconOffsetBottom;
		public static int iconOffsetLeft;

		// Tab enable/disable settings
		public static boolean inventoryTabEnabled;
		public static boolean backpackedTabEnabled;
		public static boolean travelersBackpackTabEnabled;
		public static boolean mapAtlasesTabEnabled;
		public static boolean xaerosMapTabEnabled;
		public static boolean journeyMapTabEnabled;
		public static boolean bodyDamageTabEnabled;
		public static boolean reskillableReimaginedTabEnabled;
		public static boolean ftbQuestsTabEnabled;
		public static boolean ftbTeamsTabEnabled;
		public static boolean ftbChunksTabEnabled;
		public static boolean dietTabEnabled;
		public static boolean pufferfishSkillsTabEnabled;
		public static boolean passiveSkillTreeTabEnabled;
		public static boolean sophisticatedBackpacksTabEnabled;
		public static boolean cobblemonTabEnabled;
		public static boolean arsElixirumTabEnabled;
		public static boolean arsNouveauTabEnabled;
		public static boolean l2HostilityTabEnabled;
		public static boolean l2AttributesTabEnabled;
		public static boolean l2ArtifactsTabEnabled;
		public static boolean cosmeticArmorTabEnabled;
		public static boolean modularGolemsTabEnabled;
		public static boolean motpTabEnabled;
		public static boolean advancementsTabEnabled;
		public static boolean draconicEvolutionTabEnabled;
		public static boolean brassworksMissionsTabEnabled;
		public static boolean eccentricTomeTabEnabled;
		public static boolean rpgCraftingTabEnabled;
		public static boolean biologyDictionaryTabEnabled;
		public static boolean reliableBackpacksTabEnabled;
		public static boolean wildexTabEnabled;
		public static boolean apothicAttributesTabEnabled;
		public static boolean aetherTabEnabled;
		public static boolean curiosTabEnabled;
		public static boolean epicFightTabEnabled;
		public static boolean epicSkillsTabEnabled;
		public static boolean completionistsIndexTabEnabled;
		public static boolean sdmShopTabEnabled;
		public static boolean jobsPlusTabEnabled;
		public static boolean questLogTabEnabled;
		public static boolean mapwrightTabEnabled;
		public static boolean fieldGuideTabEnabled;
		public static boolean modonomiconTabEnabled;
		public static boolean stickyInventoryTab;
		public static boolean allowEditing;

		// Custom icon settings
		public static String inventoryTabCustomIcon;
		public static int inventoryTabIconScale;
		public static int inventoryTabIconNudgeUp;
		public static int inventoryTabIconNudgeDown;
		public static int inventoryTabIconNudgeLeft;
		public static int inventoryTabIconNudgeRight;
		public static String advancementsTabCustomIcon;
		public static int advancementsTabIconScale;
		public static int advancementsTabIconNudgeUp;
		public static int advancementsTabIconNudgeDown;
		public static int advancementsTabIconNudgeLeft;
		public static int advancementsTabIconNudgeRight;
		public static String rpgCraftingTabCustomIcon;
		public static int rpgCraftingTabIconScale;
		public static int rpgCraftingTabIconNudgeUp;
		public static int rpgCraftingTabIconNudgeDown;
		public static int rpgCraftingTabIconNudgeLeft;
		public static int rpgCraftingTabIconNudgeRight;
		public static String arsElixirumTabCustomIcon;
		public static int arsElixirumTabIconScale;
		public static int arsElixirumTabIconNudgeUp;
		public static int arsElixirumTabIconNudgeDown;
		public static int arsElixirumTabIconNudgeLeft;
		public static int arsElixirumTabIconNudgeRight;
		public static String arsNouveauTabCustomIcon;
		public static int arsNouveauTabIconScale;
		public static int arsNouveauTabIconNudgeUp;
		public static int arsNouveauTabIconNudgeDown;
		public static int arsNouveauTabIconNudgeLeft;
		public static int arsNouveauTabIconNudgeRight;
		public static String backpackedTabCustomIcon;
		public static int backpackedTabIconScale;
		public static int backpackedTabIconNudgeUp;
		public static int backpackedTabIconNudgeDown;
		public static int backpackedTabIconNudgeLeft;
		public static int backpackedTabIconNudgeRight;
		public static String bodyDamageTabCustomIcon;
		public static int bodyDamageTabIconScale;
		public static int bodyDamageTabIconNudgeUp;
		public static int bodyDamageTabIconNudgeDown;
		public static int bodyDamageTabIconNudgeLeft;
		public static int bodyDamageTabIconNudgeRight;
		public static String brassworksMissionsTabCustomIcon;
		public static int brassworksMissionsTabIconScale;
		public static int brassworksMissionsTabIconNudgeUp;
		public static int brassworksMissionsTabIconNudgeDown;
		public static int brassworksMissionsTabIconNudgeLeft;
		public static int brassworksMissionsTabIconNudgeRight;
		public static String cobblemonTabCustomIcon;
		public static int cobblemonTabIconScale;
		public static int cobblemonTabIconNudgeUp;
		public static int cobblemonTabIconNudgeDown;
		public static int cobblemonTabIconNudgeLeft;
		public static int cobblemonTabIconNudgeRight;
		public static String cosmeticArmorTabCustomIcon;
		public static int cosmeticArmorTabIconScale;
		public static int cosmeticArmorTabIconNudgeUp;
		public static int cosmeticArmorTabIconNudgeDown;
		public static int cosmeticArmorTabIconNudgeLeft;
		public static int cosmeticArmorTabIconNudgeRight;
		public static String draconicEvolutionTabCustomIcon;
		public static int draconicEvolutionTabIconScale;
		public static int draconicEvolutionTabIconNudgeUp;
		public static int draconicEvolutionTabIconNudgeDown;
		public static int draconicEvolutionTabIconNudgeLeft;
		public static int draconicEvolutionTabIconNudgeRight;
		public static String eccentricTomeTabCustomIcon;
		public static int eccentricTomeTabIconScale;
		public static int eccentricTomeTabIconNudgeUp;
		public static int eccentricTomeTabIconNudgeDown;
		public static int eccentricTomeTabIconNudgeLeft;
		public static int eccentricTomeTabIconNudgeRight;
		public static String dietTabCustomIcon;
		public static int dietTabIconScale;
		public static int dietTabIconNudgeUp;
		public static int dietTabIconNudgeDown;
		public static int dietTabIconNudgeLeft;
		public static int dietTabIconNudgeRight;
		public static String ftbQuestsTabCustomIcon;
		public static int ftbQuestsTabIconScale;
		public static int ftbQuestsTabIconNudgeUp;
		public static int ftbQuestsTabIconNudgeDown;
		public static int ftbQuestsTabIconNudgeLeft;
		public static int ftbQuestsTabIconNudgeRight;
		public static String ftbTeamsTabCustomIcon;
		public static int ftbTeamsTabIconScale;
		public static int ftbTeamsTabIconNudgeUp;
		public static int ftbTeamsTabIconNudgeDown;
		public static int ftbTeamsTabIconNudgeLeft;
		public static int ftbTeamsTabIconNudgeRight;
		public static String ftbChunksTabCustomIcon;
		public static int ftbChunksTabIconScale;
		public static int ftbChunksTabIconNudgeUp;
		public static int ftbChunksTabIconNudgeDown;
		public static int ftbChunksTabIconNudgeLeft;
		public static int ftbChunksTabIconNudgeRight;
		public static String journeyMapTabCustomIcon;
		public static int journeyMapTabIconScale;
		public static int journeyMapTabIconNudgeUp;
		public static int journeyMapTabIconNudgeDown;
		public static int journeyMapTabIconNudgeLeft;
		public static int journeyMapTabIconNudgeRight;
		public static String l2ArtifactsTabCustomIcon;
		public static int l2ArtifactsTabIconScale;
		public static int l2ArtifactsTabIconNudgeUp;
		public static int l2ArtifactsTabIconNudgeDown;
		public static int l2ArtifactsTabIconNudgeLeft;
		public static int l2ArtifactsTabIconNudgeRight;
		public static String l2AttributesTabCustomIcon;
		public static int l2AttributesTabIconScale;
		public static int l2AttributesTabIconNudgeUp;
		public static int l2AttributesTabIconNudgeDown;
		public static int l2AttributesTabIconNudgeLeft;
		public static int l2AttributesTabIconNudgeRight;
		public static String l2HostilityTabCustomIcon;
		public static int l2HostilityTabIconScale;
		public static int l2HostilityTabIconNudgeUp;
		public static int l2HostilityTabIconNudgeDown;
		public static int l2HostilityTabIconNudgeLeft;
		public static int l2HostilityTabIconNudgeRight;
		public static String mapAtlasesTabCustomIcon;
		public static int mapAtlasesTabIconScale;
		public static int mapAtlasesTabIconNudgeUp;
		public static int mapAtlasesTabIconNudgeDown;
		public static int mapAtlasesTabIconNudgeLeft;
		public static int mapAtlasesTabIconNudgeRight;
		public static String modularGolemsTabCustomIcon;
		public static int modularGolemsTabIconScale;
		public static int modularGolemsTabIconNudgeUp;
		public static int modularGolemsTabIconNudgeDown;
		public static int modularGolemsTabIconNudgeLeft;
		public static int modularGolemsTabIconNudgeRight;
		public static String motpTabCustomIcon;
		public static int motpTabIconScale;
		public static int motpTabIconNudgeUp;
		public static int motpTabIconNudgeDown;
		public static int motpTabIconNudgeLeft;
		public static int motpTabIconNudgeRight;
		public static String passiveSkillTreeTabCustomIcon;
		public static int passiveSkillTreeTabIconScale;
		public static int passiveSkillTreeTabIconNudgeUp;
		public static int passiveSkillTreeTabIconNudgeDown;
		public static int passiveSkillTreeTabIconNudgeLeft;
		public static int passiveSkillTreeTabIconNudgeRight;
		public static String pufferfishSkillsTabCustomIcon;
		public static int pufferfishSkillsTabIconScale;
		public static int pufferfishSkillsTabIconNudgeUp;
		public static int pufferfishSkillsTabIconNudgeDown;
		public static int pufferfishSkillsTabIconNudgeLeft;
		public static int pufferfishSkillsTabIconNudgeRight;
		public static String reskillableReimaginedTabCustomIcon;
		public static int reskillableReimaginedTabIconScale;
		public static int reskillableReimaginedTabIconNudgeUp;
		public static int reskillableReimaginedTabIconNudgeDown;
		public static int reskillableReimaginedTabIconNudgeLeft;
		public static int reskillableReimaginedTabIconNudgeRight;
		public static String sophisticatedBackpacksTabCustomIcon;
		public static int sophisticatedBackpacksTabIconScale;
		public static int sophisticatedBackpacksTabIconNudgeUp;
		public static int sophisticatedBackpacksTabIconNudgeDown;
		public static int sophisticatedBackpacksTabIconNudgeLeft;
		public static int sophisticatedBackpacksTabIconNudgeRight;
		public static String travelersBackpackTabCustomIcon;
		public static int travelersBackpackTabIconScale;
		public static int travelersBackpackTabIconNudgeUp;
		public static int travelersBackpackTabIconNudgeDown;
		public static int travelersBackpackTabIconNudgeLeft;
		public static int travelersBackpackTabIconNudgeRight;
		public static String xaerosMapTabCustomIcon;
		public static int xaerosMapTabIconScale;
		public static int xaerosMapTabIconNudgeUp;
		public static int xaerosMapTabIconNudgeDown;
		public static int xaerosMapTabIconNudgeLeft;
		public static int xaerosMapTabIconNudgeRight;
		public static String biologyDictionaryTabCustomIcon;
		public static int biologyDictionaryTabIconScale;
		public static int biologyDictionaryTabIconNudgeUp;
		public static int biologyDictionaryTabIconNudgeDown;
		public static int biologyDictionaryTabIconNudgeLeft;
		public static int biologyDictionaryTabIconNudgeRight;
		public static String reliableBackpacksTabCustomIcon;
		public static int reliableBackpacksTabIconScale;
		public static int reliableBackpacksTabIconNudgeUp;
		public static int reliableBackpacksTabIconNudgeDown;
		public static int reliableBackpacksTabIconNudgeLeft;
		public static int reliableBackpacksTabIconNudgeRight;
		public static String wildexTabCustomIcon;
		public static int wildexTabIconScale;
		public static int wildexTabIconNudgeUp;
		public static int wildexTabIconNudgeDown;
		public static int wildexTabIconNudgeLeft;
		public static int wildexTabIconNudgeRight;
		public static String apothicAttributesTabCustomIcon;
		public static int apothicAttributesTabIconScale;
		public static int apothicAttributesTabIconNudgeUp;
		public static int apothicAttributesTabIconNudgeDown;
		public static int apothicAttributesTabIconNudgeLeft;
		public static int apothicAttributesTabIconNudgeRight;
		public static String aetherTabCustomIcon;
		public static int aetherTabIconScale;
		public static int aetherTabIconNudgeUp;
		public static int aetherTabIconNudgeDown;
		public static int aetherTabIconNudgeLeft;
		public static int aetherTabIconNudgeRight;
		public static String curiosTabCustomIcon;
		public static int curiosTabIconScale;
		public static int curiosTabIconNudgeUp;
		public static int curiosTabIconNudgeDown;
		public static int curiosTabIconNudgeLeft;
		public static int curiosTabIconNudgeRight;
		public static String epicFightTabCustomIcon;
		public static int epicFightTabIconScale;
		public static int epicFightTabIconNudgeUp;
		public static int epicFightTabIconNudgeDown;
		public static int epicFightTabIconNudgeLeft;
		public static int epicFightTabIconNudgeRight;
		public static String epicSkillsTabCustomIcon;
		public static int epicSkillsTabIconScale;
		public static int epicSkillsTabIconNudgeUp;
		public static int epicSkillsTabIconNudgeDown;
		public static int epicSkillsTabIconNudgeLeft;
		public static int epicSkillsTabIconNudgeRight;
		public static String completionistsIndexTabCustomIcon;
		public static int completionistsIndexTabIconScale;
		public static int completionistsIndexTabIconNudgeUp;
		public static int completionistsIndexTabIconNudgeDown;
		public static int completionistsIndexTabIconNudgeLeft;
		public static int completionistsIndexTabIconNudgeRight;
		public static String sdmShopTabCustomIcon;
		public static int sdmShopTabIconScale;
		public static int sdmShopTabIconNudgeUp;
		public static int sdmShopTabIconNudgeDown;
		public static int sdmShopTabIconNudgeLeft;
		public static int sdmShopTabIconNudgeRight;
		public static String jobsPlusTabCustomIcon;
		public static int jobsPlusTabIconScale;
		public static int jobsPlusTabIconNudgeUp;
		public static int jobsPlusTabIconNudgeDown;
		public static int jobsPlusTabIconNudgeLeft;
		public static int jobsPlusTabIconNudgeRight;
		public static String questLogTabCustomIcon;
		public static int questLogTabIconScale;
		public static int questLogTabIconNudgeUp;
		public static int questLogTabIconNudgeDown;
		public static int questLogTabIconNudgeLeft;
		public static int questLogTabIconNudgeRight;
		public static String mapwrightTabCustomIcon;
		public static int mapwrightTabIconScale;
		public static int mapwrightTabIconNudgeUp;
		public static int mapwrightTabIconNudgeDown;
		public static int mapwrightTabIconNudgeLeft;
		public static int mapwrightTabIconNudgeRight;
		public static String fieldGuideTabCustomIcon;
		public static int fieldGuideTabIconScale;
		public static int fieldGuideTabIconNudgeUp;
		public static int fieldGuideTabIconNudgeDown;
		public static int fieldGuideTabIconNudgeLeft;
		public static int fieldGuideTabIconNudgeRight;
		public static String modonomiconTabCustomIcon;
		public static int modonomiconTabIconScale;
		public static int modonomiconTabIconNudgeUp;
		public static int modonomiconTabIconNudgeDown;
		public static int modonomiconTabIconNudgeLeft;
		public static int modonomiconTabIconNudgeRight;

		// Custom tabs settings
		public static boolean customTabsEnabled;
		public static boolean customTabsDebugLogging;

		// Nearby-container tabs (chests / barrels / etc. discovered around the player)
		public static boolean nearbyContainersTabEnabled;
		public static int nearbyContainersTabRange;
		public static boolean nearbyContainersTabRequireLineOfSight;

		// Tab display visibility settings
		public static TabDisplayVisibility inventoryTabDisplayVisibility;
		public static TabDisplayVisibility advancementsTabDisplayVisibility;
		public static TabDisplayVisibility arsElixirumTabDisplayVisibility;
		public static TabDisplayVisibility arsNouveauTabDisplayVisibility;
		public static TabDisplayVisibility backpackedTabDisplayVisibility;
		public static TabDisplayVisibility bodyDamageTabDisplayVisibility;
		public static TabDisplayVisibility cobblemonTabDisplayVisibility;
		public static TabDisplayVisibility cosmeticArmorTabDisplayVisibility;
		public static TabDisplayVisibility draconicEvolutionTabDisplayVisibility;
		public static TabDisplayVisibility dietTabDisplayVisibility;
		public static TabDisplayVisibility ftbQuestsTabDisplayVisibility;
		public static TabDisplayVisibility ftbTeamsTabDisplayVisibility;
		public static TabDisplayVisibility ftbChunksTabDisplayVisibility;
		public static TabDisplayVisibility journeyMapTabDisplayVisibility;
		public static TabDisplayVisibility l2ArtifactsTabDisplayVisibility;
		public static TabDisplayVisibility l2AttributesTabDisplayVisibility;
		public static TabDisplayVisibility l2HostilityTabDisplayVisibility;
		public static TabDisplayVisibility mapAtlasesTabDisplayVisibility;
		public static TabDisplayVisibility modularGolemsTabDisplayVisibility;
		public static TabDisplayVisibility motpTabDisplayVisibility;
		public static TabDisplayVisibility passiveSkillTreeTabDisplayVisibility;
		public static TabDisplayVisibility pufferfishSkillsTabDisplayVisibility;
		public static TabDisplayVisibility reskillableReimaginedTabDisplayVisibility;
		public static TabDisplayVisibility sophisticatedBackpacksTabDisplayVisibility;
		public static TabDisplayVisibility travelersBackpackTabDisplayVisibility;
		public static TabDisplayVisibility xaerosMapTabDisplayVisibility;
		public static TabDisplayVisibility brassworksMissionsTabDisplayVisibility;
		public static TabDisplayVisibility eccentricTomeTabDisplayVisibility;
		public static TabDisplayVisibility rpgCraftingTabDisplayVisibility;
		public static TabDisplayVisibility biologyDictionaryTabDisplayVisibility;
		public static TabDisplayVisibility reliableBackpacksTabDisplayVisibility;
		public static TabDisplayVisibility wildexTabDisplayVisibility;
		public static TabDisplayVisibility curiosTabDisplayVisibility;
		public static TabDisplayVisibility epicFightTabDisplayVisibility;
		public static TabDisplayVisibility epicSkillsTabDisplayVisibility;
		public static TabDisplayVisibility completionistsIndexTabDisplayVisibility;
		public static TabDisplayVisibility sdmShopTabDisplayVisibility;
		public static TabDisplayVisibility jobsPlusTabDisplayVisibility;
		public static TabDisplayVisibility questLogTabDisplayVisibility;
		public static TabDisplayVisibility mapwrightTabDisplayVisibility;
		public static TabDisplayVisibility fieldGuideTabDisplayVisibility;
		public static TabDisplayVisibility modonomiconTabDisplayVisibility;

		// Tab order overrides
		public static int inventoryTabOrder;
		public static int backpackedTabOrder;
		public static int travelersBackpackTabOrder;
		public static int bodyDamageTabOrder;
		public static int reskillableReimaginedTabOrder;
		public static int ftbQuestsTabOrder;
		public static int ftbTeamsTabOrder;
		public static int ftbChunksTabOrder;
		public static int mapAtlasesTabOrder;
		public static int xaerosMapTabOrder;
		public static int journeyMapTabOrder;
		public static int dietTabOrder;
		public static int pufferfishSkillsTabOrder;
		public static int passiveSkillTreeTabOrder;
		public static int sophisticatedBackpacksTabOrder;
		public static BackpackSlot sophisticatedBackpacksPreferredSlot;
		public static int cobblemonTabOrder;
		public static int modularGolemsTabOrder;
		public static int motpTabOrder;
		public static int arsElixirumTabOrder;
		public static int arsNouveauTabOrder;
		public static int l2HostilityTabOrder;
		public static int l2AttributesTabOrder;
		public static int l2ArtifactsTabOrder;
		public static int cosmeticArmorTabOrder;
		public static int advancementsTabOrder;
		public static int draconicEvolutionTabOrder;
		public static int brassworksMissionsTabOrder;
		public static int eccentricTomeTabOrder;
		public static int rpgCraftingTabOrder;
		public static int biologyDictionaryTabOrder;
		public static int reliableBackpacksTabOrder;
		public static int wildexTabOrder;
		public static int apothicAttributesTabOrder;
		public static int aetherTabOrder;
		public static int curiosTabOrder;
		public static int epicFightTabOrder;
		public static int epicSkillsTabOrder;
		public static int completionistsIndexTabOrder;
		public static int sdmShopTabOrder;
		public static int jobsPlusTabOrder;
		public static int questLogTabOrder;
		public static int mapwrightTabOrder;
		public static int fieldGuideTabOrder;
		public static int modonomiconTabOrder;

		public static void bakeClient()
		{
			try
			{
				// Global modal-controlled settings.
				iconOffsetTop = ModTabsConfig.iconOffsetTop;
				iconOffsetRight = ModTabsConfig.iconOffsetRight;
				iconOffsetBottom = ModTabsConfig.iconOffsetBottom;
				iconOffsetLeft = ModTabsConfig.iconOffsetLeft;

				// Read from MidnightConfig fields
				inventoryTabEnabled = ModTabsConfig.inventoryTabEnabled;
				backpackedTabEnabled = ModTabsConfig.backpackedTabEnabled;
				travelersBackpackTabEnabled = ModTabsConfig.travelersBackpackTabEnabled;
				bodyDamageTabEnabled = ModTabsConfig.bodyDamageTabEnabled;
				reskillableReimaginedTabEnabled = ModTabsConfig.reskillableReimaginedTabEnabled;
				ftbQuestsTabEnabled = ModTabsConfig.ftbQuestsTabEnabled;
				ftbChunksTabEnabled = ModTabsConfig.ftbChunksTabEnabled;
				mapAtlasesTabEnabled = ModTabsConfig.mapAtlasesTabEnabled;
				xaerosMapTabEnabled = ModTabsConfig.xaerosMapTabEnabled;
				journeyMapTabEnabled = ModTabsConfig.journeyMapTabEnabled;
				ftbTeamsTabEnabled = ModTabsConfig.ftbTeamsTabEnabled;
				dietTabEnabled = ModTabsConfig.dietTabEnabled;
				pufferfishSkillsTabEnabled = ModTabsConfig.pufferfishSkillsTabEnabled;
				passiveSkillTreeTabEnabled = ModTabsConfig.passiveSkillTreeTabEnabled;
				sophisticatedBackpacksTabEnabled = ModTabsConfig.sophisticatedBackpacksTabEnabled;
				cobblemonTabEnabled = ModTabsConfig.cobblemonTabEnabled;
				arsElixirumTabEnabled = ModTabsConfig.arsElixirumTabEnabled;
				arsNouveauTabEnabled = ModTabsConfig.arsNouveauTabEnabled;

				// Additional tabs not in original config
				l2HostilityTabEnabled = ModTabsConfig.l2HostilityTabEnabled;
				l2AttributesTabEnabled = ModTabsConfig.l2AttributesTabEnabled;
				l2ArtifactsTabEnabled = ModTabsConfig.l2ArtifactsTabEnabled;
				cosmeticArmorTabEnabled = ModTabsConfig.cosmeticArmorTabEnabled;
				modularGolemsTabEnabled = ModTabsConfig.modularGolemsTabEnabled;
				motpTabEnabled = ModTabsConfig.motpTabEnabled;
				advancementsTabEnabled = ModTabsConfig.advancementsTabEnabled;
				draconicEvolutionTabEnabled = ModTabsConfig.draconicEvolutionTabEnabled;
				brassworksMissionsTabEnabled = ModTabsConfig.brassworksMissionsTabEnabled;
				eccentricTomeTabEnabled = ModTabsConfig.eccentricTomeTabEnabled;
				rpgCraftingTabEnabled = ModTabsConfig.rpgCraftingTabEnabled;
				biologyDictionaryTabEnabled = ModTabsConfig.biologyDictionaryTabEnabled;
				reliableBackpacksTabEnabled = ModTabsConfig.reliableBackpacksTabEnabled;
				wildexTabEnabled = ModTabsConfig.wildexTabEnabled;
				apothicAttributesTabEnabled = ModTabsConfig.apothicAttributesTabEnabled;
				aetherTabEnabled = ModTabsConfig.aetherTabEnabled;
				curiosTabEnabled = ModTabsConfig.curiosTabEnabled;
				epicFightTabEnabled = ModTabsConfig.epicFightTabEnabled;
				epicSkillsTabEnabled = ModTabsConfig.epicSkillsTabEnabled;
				completionistsIndexTabEnabled = ModTabsConfig.completionistsIndexTabEnabled;
				sdmShopTabEnabled = ModTabsConfig.sdmShopTabEnabled;
				jobsPlusTabEnabled = ModTabsConfig.jobsPlusTabEnabled;
				questLogTabEnabled = ModTabsConfig.questLogTabEnabled;
				mapwrightTabEnabled = ModTabsConfig.mapwrightTabEnabled;
				fieldGuideTabEnabled = ModTabsConfig.fieldGuideTabEnabled;
				modonomiconTabEnabled = ModTabsConfig.modonomiconTabEnabled;
				stickyInventoryTab = ModTabsConfig.stickyInventoryTab;
				allowEditing = ModTabsConfig.allowEditing;

				// Load custom tabs settings
				customTabsEnabled = ModTabsConfig.customTabsEnabled;
				customTabsDebugLogging = ModTabsConfig.customTabsDebugLogging;

				// Nearby-container tabs
				nearbyContainersTabEnabled = ModTabsConfig.nearbyContainersTabEnabled;
				nearbyContainersTabRange = ModTabsConfig.nearbyContainersTabRange;
				nearbyContainersTabRequireLineOfSight = ModTabsConfig.nearbyContainersTabRequireLineOfSight;

				// Load tab order overrides
				inventoryTabOrder = ModTabsConfig.inventoryTabOrder;
				backpackedTabOrder = ModTabsConfig.backpackedTabOrder;
				travelersBackpackTabOrder = ModTabsConfig.travelersBackpackTabOrder;
				bodyDamageTabOrder = ModTabsConfig.bodyDamageTabOrder;
				reskillableReimaginedTabOrder = ModTabsConfig.reskillableReimaginedTabOrder;
				ftbQuestsTabOrder = ModTabsConfig.ftbQuestsTabOrder;
				ftbTeamsTabOrder = ModTabsConfig.ftbTeamsTabOrder;
				ftbChunksTabOrder = ModTabsConfig.ftbChunksTabOrder;
				mapAtlasesTabOrder = ModTabsConfig.mapAtlasesTabOrder;
				xaerosMapTabOrder = ModTabsConfig.xaerosMapTabOrder;
				journeyMapTabOrder = ModTabsConfig.journeyMapTabOrder;
				dietTabOrder = ModTabsConfig.dietTabOrder;
				pufferfishSkillsTabOrder = ModTabsConfig.pufferfishSkillsTabOrder;
				passiveSkillTreeTabOrder = ModTabsConfig.passiveSkillTreeTabOrder;
				sophisticatedBackpacksTabOrder = ModTabsConfig.sophisticatedBackpacksTabOrder;
				sophisticatedBackpacksPreferredSlot = ModTabsConfig.sophisticatedBackpacksPreferredSlot;
				cobblemonTabOrder = ModTabsConfig.cobblemonTabOrder;
				modularGolemsTabOrder = ModTabsConfig.modularGolemsTabOrder;
				motpTabOrder = ModTabsConfig.motpTabOrder;
				arsElixirumTabOrder = ModTabsConfig.arsElixirumTabOrder;
				arsNouveauTabOrder = ModTabsConfig.arsNouveauTabOrder;
				l2HostilityTabOrder = ModTabsConfig.l2HostilityTabOrder;
				l2AttributesTabOrder = ModTabsConfig.l2AttributesTabOrder;
				l2ArtifactsTabOrder = ModTabsConfig.l2ArtifactsTabOrder;
				cosmeticArmorTabOrder = ModTabsConfig.cosmeticArmorTabOrder;
				advancementsTabOrder = ModTabsConfig.advancementsTabOrder;
				draconicEvolutionTabOrder = ModTabsConfig.draconicEvolutionTabOrder;
				brassworksMissionsTabOrder = ModTabsConfig.brassworksMissionsTabOrder;
				eccentricTomeTabOrder = ModTabsConfig.eccentricTomeTabOrder;
				rpgCraftingTabOrder = ModTabsConfig.rpgCraftingTabOrder;
				biologyDictionaryTabOrder = ModTabsConfig.biologyDictionaryTabOrder;
				reliableBackpacksTabOrder = ModTabsConfig.reliableBackpacksTabOrder;
				wildexTabOrder = ModTabsConfig.wildexTabOrder;
				apothicAttributesTabOrder = ModTabsConfig.apothicAttributesTabOrder;
				aetherTabOrder = ModTabsConfig.aetherTabOrder;
				curiosTabOrder = ModTabsConfig.curiosTabOrder;
				epicFightTabOrder = ModTabsConfig.epicFightTabOrder;
				epicSkillsTabOrder = ModTabsConfig.epicSkillsTabOrder;
				completionistsIndexTabOrder = ModTabsConfig.completionistsIndexTabOrder;
				sdmShopTabOrder = ModTabsConfig.sdmShopTabOrder;
				jobsPlusTabOrder = ModTabsConfig.jobsPlusTabOrder;
				questLogTabOrder = ModTabsConfig.questLogTabOrder;
				mapwrightTabOrder = ModTabsConfig.mapwrightTabOrder;
				fieldGuideTabOrder = ModTabsConfig.fieldGuideTabOrder;
				modonomiconTabOrder = ModTabsConfig.modonomiconTabOrder;

				// Load tab display visibility settings
				inventoryTabDisplayVisibility = ModTabsConfig.inventoryTabDisplayVisibility;
				advancementsTabDisplayVisibility = ModTabsConfig.advancementsTabDisplayVisibility;
				arsElixirumTabDisplayVisibility = ModTabsConfig.arsElixirumTabDisplayVisibility;
				arsNouveauTabDisplayVisibility = ModTabsConfig.arsNouveauTabDisplayVisibility;
				backpackedTabDisplayVisibility = ModTabsConfig.backpackedTabDisplayVisibility;
				bodyDamageTabDisplayVisibility = ModTabsConfig.bodyDamageTabDisplayVisibility;
				brassworksMissionsTabDisplayVisibility = ModTabsConfig.brassworksMissionsTabDisplayVisibility;
				cobblemonTabDisplayVisibility = ModTabsConfig.cobblemonTabDisplayVisibility;
				cosmeticArmorTabDisplayVisibility = ModTabsConfig.cosmeticArmorTabDisplayVisibility;
				draconicEvolutionTabDisplayVisibility = ModTabsConfig.draconicEvolutionTabDisplayVisibility;
				eccentricTomeTabDisplayVisibility = ModTabsConfig.eccentricTomeTabDisplayVisibility;
				dietTabDisplayVisibility = ModTabsConfig.dietTabDisplayVisibility;
				ftbQuestsTabDisplayVisibility = ModTabsConfig.ftbQuestsTabDisplayVisibility;
				ftbTeamsTabDisplayVisibility = ModTabsConfig.ftbTeamsTabDisplayVisibility;
				ftbChunksTabDisplayVisibility = ModTabsConfig.ftbChunksTabDisplayVisibility;
				journeyMapTabDisplayVisibility = ModTabsConfig.journeyMapTabDisplayVisibility;
				l2ArtifactsTabDisplayVisibility = ModTabsConfig.l2ArtifactsTabDisplayVisibility;
				l2AttributesTabDisplayVisibility = ModTabsConfig.l2AttributesTabDisplayVisibility;
				l2HostilityTabDisplayVisibility = ModTabsConfig.l2HostilityTabDisplayVisibility;
				mapAtlasesTabDisplayVisibility = ModTabsConfig.mapAtlasesTabDisplayVisibility;
				modularGolemsTabDisplayVisibility = ModTabsConfig.modularGolemsTabDisplayVisibility;
				motpTabDisplayVisibility = ModTabsConfig.motpTabDisplayVisibility;
				passiveSkillTreeTabDisplayVisibility = ModTabsConfig.passiveSkillTreeTabDisplayVisibility;
				pufferfishSkillsTabDisplayVisibility = ModTabsConfig.pufferfishSkillsTabDisplayVisibility;
				reskillableReimaginedTabDisplayVisibility = ModTabsConfig.reskillableReimaginedTabDisplayVisibility;
				sophisticatedBackpacksTabDisplayVisibility = ModTabsConfig.sophisticatedBackpacksTabDisplayVisibility;
				travelersBackpackTabDisplayVisibility = ModTabsConfig.travelersBackpackTabDisplayVisibility;
				xaerosMapTabDisplayVisibility = ModTabsConfig.xaerosMapTabDisplayVisibility;
				rpgCraftingTabDisplayVisibility = ModTabsConfig.advancementsTabDisplayVisibility; // Shares config with advancements
				biologyDictionaryTabDisplayVisibility = ModTabsConfig.biologyDictionaryTabDisplayVisibility;
				reliableBackpacksTabDisplayVisibility = ModTabsConfig.reliableBackpacksTabDisplayVisibility;
				wildexTabDisplayVisibility = ModTabsConfig.wildexTabDisplayVisibility;
				curiosTabDisplayVisibility = ModTabsConfig.curiosTabDisplayVisibility;
				epicFightTabDisplayVisibility = ModTabsConfig.epicFightTabDisplayVisibility;
				epicSkillsTabDisplayVisibility = ModTabsConfig.epicSkillsTabDisplayVisibility;
				completionistsIndexTabDisplayVisibility = ModTabsConfig.completionistsIndexTabDisplayVisibility;
				sdmShopTabDisplayVisibility = ModTabsConfig.sdmShopTabDisplayVisibility;
				jobsPlusTabDisplayVisibility = ModTabsConfig.jobsPlusTabDisplayVisibility;
				questLogTabDisplayVisibility = ModTabsConfig.questLogTabDisplayVisibility;
				mapwrightTabDisplayVisibility = ModTabsConfig.mapwrightTabDisplayVisibility;
				fieldGuideTabDisplayVisibility = ModTabsConfig.fieldGuideTabDisplayVisibility;
				modonomiconTabDisplayVisibility = ModTabsConfig.modonomiconTabDisplayVisibility;

				// Load custom icon settings
				inventoryTabCustomIcon = ModTabsConfig.inventoryTabCustomIcon;
				inventoryTabIconScale = ModTabsConfig.inventoryTabIconScale;
				inventoryTabIconNudgeUp = ModTabsConfig.inventoryTabIconNudgeUp;
				inventoryTabIconNudgeDown = ModTabsConfig.inventoryTabIconNudgeDown;
				inventoryTabIconNudgeLeft = ModTabsConfig.inventoryTabIconNudgeLeft;
				inventoryTabIconNudgeRight = ModTabsConfig.inventoryTabIconNudgeRight;
				advancementsTabCustomIcon = ModTabsConfig.advancementsTabCustomIcon;
				advancementsTabIconScale = ModTabsConfig.advancementsTabIconScale;
				advancementsTabIconNudgeUp = ModTabsConfig.advancementsTabIconNudgeUp;
				advancementsTabIconNudgeDown = ModTabsConfig.advancementsTabIconNudgeDown;
				advancementsTabIconNudgeLeft = ModTabsConfig.advancementsTabIconNudgeLeft;
				advancementsTabIconNudgeRight = ModTabsConfig.advancementsTabIconNudgeRight;
				rpgCraftingTabCustomIcon = ModTabsConfig.rpgCraftingTabCustomIcon;
				rpgCraftingTabIconScale = ModTabsConfig.rpgCraftingTabIconScale;
				rpgCraftingTabIconNudgeUp = ModTabsConfig.rpgCraftingTabIconNudgeUp;
				rpgCraftingTabIconNudgeDown = ModTabsConfig.rpgCraftingTabIconNudgeDown;
				rpgCraftingTabIconNudgeLeft = ModTabsConfig.rpgCraftingTabIconNudgeLeft;
				rpgCraftingTabIconNudgeRight = ModTabsConfig.rpgCraftingTabIconNudgeRight;
				arsElixirumTabCustomIcon = ModTabsConfig.arsElixirumTabCustomIcon;
				arsElixirumTabIconScale = ModTabsConfig.arsElixirumTabIconScale;
				arsElixirumTabIconNudgeUp = ModTabsConfig.arsElixirumTabIconNudgeUp;
				arsElixirumTabIconNudgeDown = ModTabsConfig.arsElixirumTabIconNudgeDown;
				arsElixirumTabIconNudgeLeft = ModTabsConfig.arsElixirumTabIconNudgeLeft;
				arsElixirumTabIconNudgeRight = ModTabsConfig.arsElixirumTabIconNudgeRight;
				arsNouveauTabCustomIcon = ModTabsConfig.arsNouveauTabCustomIcon;
				arsNouveauTabIconScale = ModTabsConfig.arsNouveauTabIconScale;
				arsNouveauTabIconNudgeUp = ModTabsConfig.arsNouveauTabIconNudgeUp;
				arsNouveauTabIconNudgeDown = ModTabsConfig.arsNouveauTabIconNudgeDown;
				arsNouveauTabIconNudgeLeft = ModTabsConfig.arsNouveauTabIconNudgeLeft;
				arsNouveauTabIconNudgeRight = ModTabsConfig.arsNouveauTabIconNudgeRight;
				backpackedTabCustomIcon = ModTabsConfig.backpackedTabCustomIcon;
				backpackedTabIconScale = ModTabsConfig.backpackedTabIconScale;
				backpackedTabIconNudgeUp = ModTabsConfig.backpackedTabIconNudgeUp;
				backpackedTabIconNudgeDown = ModTabsConfig.backpackedTabIconNudgeDown;
				backpackedTabIconNudgeLeft = ModTabsConfig.backpackedTabIconNudgeLeft;
				backpackedTabIconNudgeRight = ModTabsConfig.backpackedTabIconNudgeRight;
				bodyDamageTabCustomIcon = ModTabsConfig.bodyDamageTabCustomIcon;
				bodyDamageTabIconScale = ModTabsConfig.bodyDamageTabIconScale;
				bodyDamageTabIconNudgeUp = ModTabsConfig.bodyDamageTabIconNudgeUp;
				bodyDamageTabIconNudgeDown = ModTabsConfig.bodyDamageTabIconNudgeDown;
				bodyDamageTabIconNudgeLeft = ModTabsConfig.bodyDamageTabIconNudgeLeft;
				bodyDamageTabIconNudgeRight = ModTabsConfig.bodyDamageTabIconNudgeRight;
				brassworksMissionsTabCustomIcon = ModTabsConfig.brassworksMissionsTabCustomIcon;
				brassworksMissionsTabIconScale = ModTabsConfig.brassworksMissionsTabIconScale;
				brassworksMissionsTabIconNudgeUp = ModTabsConfig.brassworksMissionsTabIconNudgeUp;
				brassworksMissionsTabIconNudgeDown = ModTabsConfig.brassworksMissionsTabIconNudgeDown;
				brassworksMissionsTabIconNudgeLeft = ModTabsConfig.brassworksMissionsTabIconNudgeLeft;
				brassworksMissionsTabIconNudgeRight = ModTabsConfig.brassworksMissionsTabIconNudgeRight;
				cobblemonTabCustomIcon = ModTabsConfig.cobblemonTabCustomIcon;
				cobblemonTabIconScale = ModTabsConfig.cobblemonTabIconScale;
				cobblemonTabIconNudgeUp = ModTabsConfig.cobblemonTabIconNudgeUp;
				cobblemonTabIconNudgeDown = ModTabsConfig.cobblemonTabIconNudgeDown;
				cobblemonTabIconNudgeLeft = ModTabsConfig.cobblemonTabIconNudgeLeft;
				cobblemonTabIconNudgeRight = ModTabsConfig.cobblemonTabIconNudgeRight;
				cosmeticArmorTabCustomIcon = ModTabsConfig.cosmeticArmorTabCustomIcon;
				cosmeticArmorTabIconScale = ModTabsConfig.cosmeticArmorTabIconScale;
				cosmeticArmorTabIconNudgeUp = ModTabsConfig.cosmeticArmorTabIconNudgeUp;
				cosmeticArmorTabIconNudgeDown = ModTabsConfig.cosmeticArmorTabIconNudgeDown;
				cosmeticArmorTabIconNudgeLeft = ModTabsConfig.cosmeticArmorTabIconNudgeLeft;
				cosmeticArmorTabIconNudgeRight = ModTabsConfig.cosmeticArmorTabIconNudgeRight;
				draconicEvolutionTabCustomIcon = ModTabsConfig.draconicEvolutionTabCustomIcon;
				draconicEvolutionTabIconScale = ModTabsConfig.draconicEvolutionTabIconScale;
				draconicEvolutionTabIconNudgeUp = ModTabsConfig.draconicEvolutionTabIconNudgeUp;
				draconicEvolutionTabIconNudgeDown = ModTabsConfig.draconicEvolutionTabIconNudgeDown;
				draconicEvolutionTabIconNudgeLeft = ModTabsConfig.draconicEvolutionTabIconNudgeLeft;
				draconicEvolutionTabIconNudgeRight = ModTabsConfig.draconicEvolutionTabIconNudgeRight;
				eccentricTomeTabCustomIcon = ModTabsConfig.eccentricTomeTabCustomIcon;
				eccentricTomeTabIconScale = ModTabsConfig.eccentricTomeTabIconScale;
				eccentricTomeTabIconNudgeUp = ModTabsConfig.eccentricTomeTabIconNudgeUp;
				eccentricTomeTabIconNudgeDown = ModTabsConfig.eccentricTomeTabIconNudgeDown;
				eccentricTomeTabIconNudgeLeft = ModTabsConfig.eccentricTomeTabIconNudgeLeft;
				eccentricTomeTabIconNudgeRight = ModTabsConfig.eccentricTomeTabIconNudgeRight;
				dietTabCustomIcon = ModTabsConfig.dietTabCustomIcon;
				dietTabIconScale = ModTabsConfig.dietTabIconScale;
				dietTabIconNudgeUp = ModTabsConfig.dietTabIconNudgeUp;
				dietTabIconNudgeDown = ModTabsConfig.dietTabIconNudgeDown;
				dietTabIconNudgeLeft = ModTabsConfig.dietTabIconNudgeLeft;
				dietTabIconNudgeRight = ModTabsConfig.dietTabIconNudgeRight;
				ftbQuestsTabCustomIcon = ModTabsConfig.ftbQuestsTabCustomIcon;
				ftbQuestsTabIconScale = ModTabsConfig.ftbQuestsTabIconScale;
				ftbQuestsTabIconNudgeUp = ModTabsConfig.ftbQuestsTabIconNudgeUp;
				ftbQuestsTabIconNudgeDown = ModTabsConfig.ftbQuestsTabIconNudgeDown;
				ftbQuestsTabIconNudgeLeft = ModTabsConfig.ftbQuestsTabIconNudgeLeft;
				ftbQuestsTabIconNudgeRight = ModTabsConfig.ftbQuestsTabIconNudgeRight;
				ftbTeamsTabCustomIcon = ModTabsConfig.ftbTeamsTabCustomIcon;
				ftbTeamsTabIconScale = ModTabsConfig.ftbTeamsTabIconScale;
				ftbTeamsTabIconNudgeUp = ModTabsConfig.ftbTeamsTabIconNudgeUp;
				ftbTeamsTabIconNudgeDown = ModTabsConfig.ftbTeamsTabIconNudgeDown;
				ftbTeamsTabIconNudgeLeft = ModTabsConfig.ftbTeamsTabIconNudgeLeft;
				ftbTeamsTabIconNudgeRight = ModTabsConfig.ftbTeamsTabIconNudgeRight;
				ftbChunksTabCustomIcon = ModTabsConfig.ftbChunksTabCustomIcon;
				ftbChunksTabIconScale = ModTabsConfig.ftbChunksTabIconScale;
				ftbChunksTabIconNudgeUp = ModTabsConfig.ftbChunksTabIconNudgeUp;
				ftbChunksTabIconNudgeDown = ModTabsConfig.ftbChunksTabIconNudgeDown;
				ftbChunksTabIconNudgeLeft = ModTabsConfig.ftbChunksTabIconNudgeLeft;
				ftbChunksTabIconNudgeRight = ModTabsConfig.ftbChunksTabIconNudgeRight;
				journeyMapTabCustomIcon = ModTabsConfig.journeyMapTabCustomIcon;
				journeyMapTabIconScale = ModTabsConfig.journeyMapTabIconScale;
				journeyMapTabIconNudgeUp = ModTabsConfig.journeyMapTabIconNudgeUp;
				journeyMapTabIconNudgeDown = ModTabsConfig.journeyMapTabIconNudgeDown;
				journeyMapTabIconNudgeLeft = ModTabsConfig.journeyMapTabIconNudgeLeft;
				journeyMapTabIconNudgeRight = ModTabsConfig.journeyMapTabIconNudgeRight;
				l2ArtifactsTabCustomIcon = ModTabsConfig.l2ArtifactsTabCustomIcon;
				l2ArtifactsTabIconScale = ModTabsConfig.l2ArtifactsTabIconScale;
				l2ArtifactsTabIconNudgeUp = ModTabsConfig.l2ArtifactsTabIconNudgeUp;
				l2ArtifactsTabIconNudgeDown = ModTabsConfig.l2ArtifactsTabIconNudgeDown;
				l2ArtifactsTabIconNudgeLeft = ModTabsConfig.l2ArtifactsTabIconNudgeLeft;
				l2ArtifactsTabIconNudgeRight = ModTabsConfig.l2ArtifactsTabIconNudgeRight;
				l2AttributesTabCustomIcon = ModTabsConfig.l2AttributesTabCustomIcon;
				l2AttributesTabIconScale = ModTabsConfig.l2AttributesTabIconScale;
				l2AttributesTabIconNudgeUp = ModTabsConfig.l2AttributesTabIconNudgeUp;
				l2AttributesTabIconNudgeDown = ModTabsConfig.l2AttributesTabIconNudgeDown;
				l2AttributesTabIconNudgeLeft = ModTabsConfig.l2AttributesTabIconNudgeLeft;
				l2AttributesTabIconNudgeRight = ModTabsConfig.l2AttributesTabIconNudgeRight;
				l2HostilityTabCustomIcon = ModTabsConfig.l2HostilityTabCustomIcon;
				l2HostilityTabIconScale = ModTabsConfig.l2HostilityTabIconScale;
				l2HostilityTabIconNudgeUp = ModTabsConfig.l2HostilityTabIconNudgeUp;
				l2HostilityTabIconNudgeDown = ModTabsConfig.l2HostilityTabIconNudgeDown;
				l2HostilityTabIconNudgeLeft = ModTabsConfig.l2HostilityTabIconNudgeLeft;
				l2HostilityTabIconNudgeRight = ModTabsConfig.l2HostilityTabIconNudgeRight;
				mapAtlasesTabCustomIcon = ModTabsConfig.mapAtlasesTabCustomIcon;
				mapAtlasesTabIconScale = ModTabsConfig.mapAtlasesTabIconScale;
				mapAtlasesTabIconNudgeUp = ModTabsConfig.mapAtlasesTabIconNudgeUp;
				mapAtlasesTabIconNudgeDown = ModTabsConfig.mapAtlasesTabIconNudgeDown;
				mapAtlasesTabIconNudgeLeft = ModTabsConfig.mapAtlasesTabIconNudgeLeft;
				mapAtlasesTabIconNudgeRight = ModTabsConfig.mapAtlasesTabIconNudgeRight;
				modularGolemsTabCustomIcon = ModTabsConfig.modularGolemsTabCustomIcon;
				modularGolemsTabIconScale = ModTabsConfig.modularGolemsTabIconScale;
				modularGolemsTabIconNudgeUp = ModTabsConfig.modularGolemsTabIconNudgeUp;
				modularGolemsTabIconNudgeDown = ModTabsConfig.modularGolemsTabIconNudgeDown;
				modularGolemsTabIconNudgeLeft = ModTabsConfig.modularGolemsTabIconNudgeLeft;
				modularGolemsTabIconNudgeRight = ModTabsConfig.modularGolemsTabIconNudgeRight;
				motpTabCustomIcon = ModTabsConfig.motpTabCustomIcon;
				motpTabIconScale = ModTabsConfig.motpTabIconScale;
				motpTabIconNudgeUp = ModTabsConfig.motpTabIconNudgeUp;
				motpTabIconNudgeDown = ModTabsConfig.motpTabIconNudgeDown;
				motpTabIconNudgeLeft = ModTabsConfig.motpTabIconNudgeLeft;
				motpTabIconNudgeRight = ModTabsConfig.motpTabIconNudgeRight;
				passiveSkillTreeTabCustomIcon = ModTabsConfig.passiveSkillTreeTabCustomIcon;
				passiveSkillTreeTabIconScale = ModTabsConfig.passiveSkillTreeTabIconScale;
				passiveSkillTreeTabIconNudgeUp = ModTabsConfig.passiveSkillTreeTabIconNudgeUp;
				passiveSkillTreeTabIconNudgeDown = ModTabsConfig.passiveSkillTreeTabIconNudgeDown;
				passiveSkillTreeTabIconNudgeLeft = ModTabsConfig.passiveSkillTreeTabIconNudgeLeft;
				passiveSkillTreeTabIconNudgeRight = ModTabsConfig.passiveSkillTreeTabIconNudgeRight;
				pufferfishSkillsTabCustomIcon = ModTabsConfig.pufferfishSkillsTabCustomIcon;
				pufferfishSkillsTabIconScale = ModTabsConfig.pufferfishSkillsTabIconScale;
				pufferfishSkillsTabIconNudgeUp = ModTabsConfig.pufferfishSkillsTabIconNudgeUp;
				pufferfishSkillsTabIconNudgeDown = ModTabsConfig.pufferfishSkillsTabIconNudgeDown;
				pufferfishSkillsTabIconNudgeLeft = ModTabsConfig.pufferfishSkillsTabIconNudgeLeft;
				pufferfishSkillsTabIconNudgeRight = ModTabsConfig.pufferfishSkillsTabIconNudgeRight;
				reskillableReimaginedTabCustomIcon = ModTabsConfig.reskillableReimaginedTabCustomIcon;
				reskillableReimaginedTabIconScale = ModTabsConfig.reskillableReimaginedTabIconScale;
				reskillableReimaginedTabIconNudgeUp = ModTabsConfig.reskillableReimaginedTabIconNudgeUp;
				reskillableReimaginedTabIconNudgeDown = ModTabsConfig.reskillableReimaginedTabIconNudgeDown;
				reskillableReimaginedTabIconNudgeLeft = ModTabsConfig.reskillableReimaginedTabIconNudgeLeft;
				reskillableReimaginedTabIconNudgeRight = ModTabsConfig.reskillableReimaginedTabIconNudgeRight;
				sophisticatedBackpacksTabCustomIcon = ModTabsConfig.sophisticatedBackpacksTabCustomIcon;
				sophisticatedBackpacksTabIconScale = ModTabsConfig.sophisticatedBackpacksTabIconScale;
				sophisticatedBackpacksTabIconNudgeUp = ModTabsConfig.sophisticatedBackpacksTabIconNudgeUp;
				sophisticatedBackpacksTabIconNudgeDown = ModTabsConfig.sophisticatedBackpacksTabIconNudgeDown;
				sophisticatedBackpacksTabIconNudgeLeft = ModTabsConfig.sophisticatedBackpacksTabIconNudgeLeft;
				sophisticatedBackpacksTabIconNudgeRight = ModTabsConfig.sophisticatedBackpacksTabIconNudgeRight;
				travelersBackpackTabCustomIcon = ModTabsConfig.travelersBackpackTabCustomIcon;
				travelersBackpackTabIconScale = ModTabsConfig.travelersBackpackTabIconScale;
				travelersBackpackTabIconNudgeUp = ModTabsConfig.travelersBackpackTabIconNudgeUp;
				travelersBackpackTabIconNudgeDown = ModTabsConfig.travelersBackpackTabIconNudgeDown;
				travelersBackpackTabIconNudgeLeft = ModTabsConfig.travelersBackpackTabIconNudgeLeft;
				travelersBackpackTabIconNudgeRight = ModTabsConfig.travelersBackpackTabIconNudgeRight;
				xaerosMapTabCustomIcon = ModTabsConfig.xaerosMapTabCustomIcon;
				xaerosMapTabIconScale = ModTabsConfig.xaerosMapTabIconScale;
				xaerosMapTabIconNudgeUp = ModTabsConfig.xaerosMapTabIconNudgeUp;
				xaerosMapTabIconNudgeDown = ModTabsConfig.xaerosMapTabIconNudgeDown;
				xaerosMapTabIconNudgeLeft = ModTabsConfig.xaerosMapTabIconNudgeLeft;
				xaerosMapTabIconNudgeRight = ModTabsConfig.xaerosMapTabIconNudgeRight;
				biologyDictionaryTabCustomIcon = ModTabsConfig.biologyDictionaryTabCustomIcon;
				biologyDictionaryTabIconScale = ModTabsConfig.biologyDictionaryTabIconScale;
				biologyDictionaryTabIconNudgeUp = ModTabsConfig.biologyDictionaryTabIconNudgeUp;
				biologyDictionaryTabIconNudgeDown = ModTabsConfig.biologyDictionaryTabIconNudgeDown;
				biologyDictionaryTabIconNudgeLeft = ModTabsConfig.biologyDictionaryTabIconNudgeLeft;
				biologyDictionaryTabIconNudgeRight = ModTabsConfig.biologyDictionaryTabIconNudgeRight;
				reliableBackpacksTabCustomIcon = ModTabsConfig.reliableBackpacksTabCustomIcon;
				reliableBackpacksTabIconScale = ModTabsConfig.reliableBackpacksTabIconScale;
				reliableBackpacksTabIconNudgeUp = ModTabsConfig.reliableBackpacksTabIconNudgeUp;
				reliableBackpacksTabIconNudgeDown = ModTabsConfig.reliableBackpacksTabIconNudgeDown;
				reliableBackpacksTabIconNudgeLeft = ModTabsConfig.reliableBackpacksTabIconNudgeLeft;
				reliableBackpacksTabIconNudgeRight = ModTabsConfig.reliableBackpacksTabIconNudgeRight;
				wildexTabCustomIcon = ModTabsConfig.wildexTabCustomIcon;
				wildexTabIconScale = ModTabsConfig.wildexTabIconScale;
				wildexTabIconNudgeUp = ModTabsConfig.wildexTabIconNudgeUp;
				wildexTabIconNudgeDown = ModTabsConfig.wildexTabIconNudgeDown;
				wildexTabIconNudgeLeft = ModTabsConfig.wildexTabIconNudgeLeft;
				wildexTabIconNudgeRight = ModTabsConfig.wildexTabIconNudgeRight;
				apothicAttributesTabCustomIcon = ModTabsConfig.apothicAttributesTabCustomIcon;
				apothicAttributesTabIconScale = ModTabsConfig.apothicAttributesTabIconScale;
				apothicAttributesTabIconNudgeUp = ModTabsConfig.apothicAttributesTabIconNudgeUp;
				apothicAttributesTabIconNudgeDown = ModTabsConfig.apothicAttributesTabIconNudgeDown;
				apothicAttributesTabIconNudgeLeft = ModTabsConfig.apothicAttributesTabIconNudgeLeft;
				apothicAttributesTabIconNudgeRight = ModTabsConfig.apothicAttributesTabIconNudgeRight;
				aetherTabCustomIcon = ModTabsConfig.aetherTabCustomIcon;
				aetherTabIconScale = ModTabsConfig.aetherTabIconScale;
				aetherTabIconNudgeUp = ModTabsConfig.aetherTabIconNudgeUp;
				aetherTabIconNudgeDown = ModTabsConfig.aetherTabIconNudgeDown;
				aetherTabIconNudgeLeft = ModTabsConfig.aetherTabIconNudgeLeft;
				aetherTabIconNudgeRight = ModTabsConfig.aetherTabIconNudgeRight;
				curiosTabCustomIcon = ModTabsConfig.curiosTabCustomIcon;
				curiosTabIconScale = ModTabsConfig.curiosTabIconScale;
				curiosTabIconNudgeUp = ModTabsConfig.curiosTabIconNudgeUp;
				curiosTabIconNudgeDown = ModTabsConfig.curiosTabIconNudgeDown;
				curiosTabIconNudgeLeft = ModTabsConfig.curiosTabIconNudgeLeft;
				curiosTabIconNudgeRight = ModTabsConfig.curiosTabIconNudgeRight;
				epicFightTabCustomIcon = ModTabsConfig.epicFightTabCustomIcon;
				epicFightTabIconScale = ModTabsConfig.epicFightTabIconScale;
				epicFightTabIconNudgeUp = ModTabsConfig.epicFightTabIconNudgeUp;
				epicFightTabIconNudgeDown = ModTabsConfig.epicFightTabIconNudgeDown;
				epicFightTabIconNudgeLeft = ModTabsConfig.epicFightTabIconNudgeLeft;
				epicFightTabIconNudgeRight = ModTabsConfig.epicFightTabIconNudgeRight;
				epicSkillsTabCustomIcon = ModTabsConfig.epicSkillsTabCustomIcon;
				epicSkillsTabIconScale = ModTabsConfig.epicSkillsTabIconScale;
				epicSkillsTabIconNudgeUp = ModTabsConfig.epicSkillsTabIconNudgeUp;
				epicSkillsTabIconNudgeDown = ModTabsConfig.epicSkillsTabIconNudgeDown;
				epicSkillsTabIconNudgeLeft = ModTabsConfig.epicSkillsTabIconNudgeLeft;
				epicSkillsTabIconNudgeRight = ModTabsConfig.epicSkillsTabIconNudgeRight;
				completionistsIndexTabCustomIcon = ModTabsConfig.completionistsIndexTabCustomIcon;
				completionistsIndexTabIconScale = ModTabsConfig.completionistsIndexTabIconScale;
				completionistsIndexTabIconNudgeUp = ModTabsConfig.completionistsIndexTabIconNudgeUp;
				completionistsIndexTabIconNudgeDown = ModTabsConfig.completionistsIndexTabIconNudgeDown;
				completionistsIndexTabIconNudgeLeft = ModTabsConfig.completionistsIndexTabIconNudgeLeft;
				completionistsIndexTabIconNudgeRight = ModTabsConfig.completionistsIndexTabIconNudgeRight;
				sdmShopTabCustomIcon = ModTabsConfig.sdmShopTabCustomIcon;
				sdmShopTabIconScale = ModTabsConfig.sdmShopTabIconScale;
				sdmShopTabIconNudgeUp = ModTabsConfig.sdmShopTabIconNudgeUp;
				sdmShopTabIconNudgeDown = ModTabsConfig.sdmShopTabIconNudgeDown;
				sdmShopTabIconNudgeLeft = ModTabsConfig.sdmShopTabIconNudgeLeft;
				sdmShopTabIconNudgeRight = ModTabsConfig.sdmShopTabIconNudgeRight;
				jobsPlusTabCustomIcon = ModTabsConfig.jobsPlusTabCustomIcon;
				jobsPlusTabIconScale = ModTabsConfig.jobsPlusTabIconScale;
				jobsPlusTabIconNudgeUp = ModTabsConfig.jobsPlusTabIconNudgeUp;
				jobsPlusTabIconNudgeDown = ModTabsConfig.jobsPlusTabIconNudgeDown;
				jobsPlusTabIconNudgeLeft = ModTabsConfig.jobsPlusTabIconNudgeLeft;
				jobsPlusTabIconNudgeRight = ModTabsConfig.jobsPlusTabIconNudgeRight;
				questLogTabCustomIcon = ModTabsConfig.questLogTabCustomIcon;
				questLogTabIconScale = ModTabsConfig.questLogTabIconScale;
				questLogTabIconNudgeUp = ModTabsConfig.questLogTabIconNudgeUp;
				questLogTabIconNudgeDown = ModTabsConfig.questLogTabIconNudgeDown;
				questLogTabIconNudgeLeft = ModTabsConfig.questLogTabIconNudgeLeft;
				questLogTabIconNudgeRight = ModTabsConfig.questLogTabIconNudgeRight;
				mapwrightTabCustomIcon = ModTabsConfig.mapwrightTabCustomIcon;
				mapwrightTabIconScale = ModTabsConfig.mapwrightTabIconScale;
				mapwrightTabIconNudgeUp = ModTabsConfig.mapwrightTabIconNudgeUp;
				mapwrightTabIconNudgeDown = ModTabsConfig.mapwrightTabIconNudgeDown;
				mapwrightTabIconNudgeLeft = ModTabsConfig.mapwrightTabIconNudgeLeft;
				mapwrightTabIconNudgeRight = ModTabsConfig.mapwrightTabIconNudgeRight;
				fieldGuideTabCustomIcon = ModTabsConfig.fieldGuideTabCustomIcon;
				fieldGuideTabIconScale = ModTabsConfig.fieldGuideTabIconScale;
				fieldGuideTabIconNudgeUp = ModTabsConfig.fieldGuideTabIconNudgeUp;
				fieldGuideTabIconNudgeDown = ModTabsConfig.fieldGuideTabIconNudgeDown;
				fieldGuideTabIconNudgeLeft = ModTabsConfig.fieldGuideTabIconNudgeLeft;
				fieldGuideTabIconNudgeRight = ModTabsConfig.fieldGuideTabIconNudgeRight;
				modonomiconTabCustomIcon = ModTabsConfig.modonomiconTabCustomIcon;
				modonomiconTabIconScale = ModTabsConfig.modonomiconTabIconScale;
				modonomiconTabIconNudgeUp = ModTabsConfig.modonomiconTabIconNudgeUp;
				modonomiconTabIconNudgeDown = ModTabsConfig.modonomiconTabIconNudgeDown;
				modonomiconTabIconNudgeLeft = ModTabsConfig.modonomiconTabIconNudgeLeft;
				modonomiconTabIconNudgeRight = ModTabsConfig.modonomiconTabIconNudgeRight;
			}
			catch (Exception e)
			{
				ModTabs.LOGGER.warn("An exception was caused trying to load the client config for Mod Tabs.");
				e.printStackTrace();
			}
		}
	}
}
